### ISSUE TITLE
citation field

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#12]
Similar to [pubchem](http://pubchem.ncbi.nlm.nih.gov/compound/82400), let's add a field that shows the proper citation method for an accession number.

Could you confirm the format of how it should look?  This will then be added into the GlycanEntry page.  No need to put it in stanza.

**Comment by shinmachi** [comment]
Got confirmation citation form at DB meeting 2/24/206
[DB meeting doc](https://docs.google.com/document/d/1v5iZFl1YTgeXBZF2P3rMNh2o4e8Ht4lj7C7Wah-_HxI/edit#heading=h.aw8qd8ftz975)

**Comment by shinmachi** [comment]
Added Citation field into the new entry page
