### ISSUE TITLE
Accession number "G54440ML" does not exist

### ISSUE THREAD

**Issue by shinmachi** [glytoucan/glytoucan.github.io#121]
## 問題点
本番環境のGlycan Listで、G54440Mのエントリーページのリンクをクリックすると、Accession number "G54440ML" does not existとなる。しかし、本番環境のエンドポイントには、RDFとしてG54440Mが存在する。表示できない不具合の改善が必要。

### 画像１
![image](https://user-images.githubusercontent.com/4487545/29068024-01e13b3e-7c70-11e7-84ec-6471c0dc58c6.png)

### 画像２
![image](https://user-images.githubusercontent.com/4487545/29068044-101224c0-7c70-11e7-8abb-9d5fe7615b31.png)

## 原因かもしれないこと

https://ts.glytoucan.org/sparql
以下ののクエリで調べたところ、G54440MLのWURCSは本番環境に存在する。

```
DESCRIBE <http://rdf.glycoinfo.org/glycan/G54440ML/wurcs/2.0>

ーーーーーーーーーーーーーーーー
http://rdf.glycoinfo.org/glycan/G54440ML/wurcs/2.0	
WURCS=2.0/6,8,7/[a2122h-1b_1-5_2*NCC/3=O][a1122h-1b_1-5][a1122h-1a_1-5][a2112h-1b_1-5][a1221m-1a_1-5_?*OC][a1221m-1a_1-5]/1-1-2-3-4-5-6-4/a4-b1_a6-g1_b4-c1_c3-d1_c4-e1_e2-f1_g4-h1
```

試しに、このWURCSを本番環境の登録フォームに投げたところ、G54440MLではなく、別のAccession numberが表示された。
![image](https://user-images.githubusercontent.com/4487545/29067714-b04cc168-7c6e-11e7-8a0a-fd7749961aca.png)

しかし、G91340BRは、本番環境には存在せず、beta環境に存在する。

http://test.ts.glytoucan.org/sparql

```
DESCRIBE <http://rdf.glycoinfo.org/glycan/G91340BR>
```

よって、本番環境にbeta環境のエンドポイントが何かしらの形でリンクしてしまっているのが原因かもしれない。

**Comment by aokinobu** [comment]
> 以下ののクエリで調べたところ、G54440MLのWURCSは本番環境に存在する。

問題はベータ環境に存在しているより、なぜDescribeできるのに、存在しない？

**Comment by aokinobu** [comment]
[api サーバー](https://api.glytoucan.org)が起動していなかったようです。
再起動したところ、イメージのキャッシュをリフレッシュさして、表示するようになりました。

ご確認できましたら、クローズしてください。

**Comment by shinmachi** [comment]
対応ありがとうございます。
エントリーページの表示がされることを確認しました。また、こちらでも一回イメージのリフレッシュをする必要がありましたが、イメージの表示がされました。

問題が解決されましたので、クローズさせていただきます。

![image](https://user-images.githubusercontent.com/4487545/29102285-f6912220-7cf2-11e7-92cd-9a759aa8a8d3.png)
