### ISSUE TITLE
SSLの更新

### ISSUE THREAD

**Issue by kiyoko** [glytoucan/glytoucan.github.io#122]
２０１７年１０月１９日が現在のcertificateの期限なので、それまでに新しいものに変更してください。

**Comment by shinmachi** [comment]
From Nobu-san

ssl conversion to let's encrypt is gone.
![image](https://user-images.githubusercontent.com/4487545/31754184-f1d83852-b4d0-11e7-8500-2b2ec5f99d54.png)
