### ISSUE TITLE
翻訳システム(localization)の問題

### ISSUE THREAD

**Issue by e14m5604** [glytoucan/glytoucan.github.io#145]
ローカルで GlyTouCan を立ち上げると、次のようなエラーが出る。
HTTP Status 500 - class path resource [1.json] cannot be resolved to URL because it does not exist

この問題の恒久的な解決。

**Comment by aokinobu** [comment]
ログを見ると、http://local.glytoucan.org/　に接続しているはずです。現在アクセスできない状態のようです。

**Comment by aokinobu** [comment]
docker-composeとjenkinsの設定は古くて、修正が必要でした。一応現時点直しましたので起動しています。もう一度webページに接続すると、ダウロードするはずです。確認ください。

**Comment by e14m5604** [comment]
上記のエラーは消え、http://localhost:90 で GlyTouCan のトップページを表示できました！
