### ISSUE TITLE
GlyTouCan User Manual の更新

### ISSUE THREAD

**Issue by shinmachi** [glytoucan/glytoucan.github.io#150]
GlyTouCanのUser Manualで更新が必要な箇所が見つかったので、対応する。
http://code.glytoucan.org/manual/

## User Manual (index)
Registration
* [x] Text inputの画像を更新
* [x] File Uplodeの画像を更新

Search
* [x] Text Inputの画像を更新

## Registering Structures
Text Interface
* [x] 画像が古いので更新する

Upload Interface
* [x] 画像を修正（Displayボタンはない）

## Query Structures
Text interface
* [x] LinearCode, KCFについての記述を訂正
* [x] 画像を最新のものに更新

Accession number search
* [x] G00028MOのエントリーページの画像を最新にする

View All Motifs
* [x] G00028MOのエントリーページの画像を最新にする（同じものを利用）

**Comment by shinmachi** [comment]
User manualを一通り確認し、画像や文章の更新を行いました。

**Comment by kiyoko** [comment]
OntologyやRDFデータモデルについては？
グラフで分かれているので、example sparql queriesも更新が必要かと

**Comment by shinmachi** [comment]
>OntologyやRDFデータモデルについては？
>グラフで分かれているので、example sparql queriesも更新が必要かと
承知しました。ontology, RDFの方には手をつけていませんでした。
新しいIssueを作ります。
