### ISSUE TITLE
taxonomy 

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#24]
from ktym-san:
NCBI taxdump to OWL
https://github.com/dbcls/rdfsummit/blob/master/taxdump2owl/taxdump2owl.rb

DDBJ web site hosting the above ontology
http://tga.nig.ac.jp/ontologies/
(should be moved to ddbj.nig.ac.jp in the future)

Endpoint which contains the above owl
http://togogenome.org/sparql-test

SELECT *
FROM <http://togogenome.org/graph/taxonomy>
WHERE {
  ?tax rdfs:label "Homo sapiens" .
  ?tax ?p ?o .
}
LIMIT 100

or use UniProt's endpoint for http://purl.uniprot.org/taxonomy/9606

**Comment by aokinobu** [comment]
sample page showing how to search for taxonomy: http://togogenome.org/

**Comment by aokinobu** [comment]
stored on test.ts.glytoucan.org, graph: http://ddbj.nig.ac.jp/ontologies/taxonomy/
on macpro: /opt/virtuoso/taxonomy.ttl.gz

**Comment by shinmachi** [comment]
Does exist sparql endpoint of DDBJ?
- Not found
- Only ontology RDF file useable.

Where is endpoint that is loaded taxonomy RDF? 
- The UniProt endpoint useable.
   - http://sparql.uniprot.org/

Which we should use it?
- DDBJ taxonomy ontology RDF file
- UniProt endpoint

**Comment by kiyoko** [comment]
If there are no federated query problems, prefer to use UniProt.
If it's still unstable, then use DDBJ in the meantime.

**Comment by aokinobu** [comment]
external data partner: https://github.com/glytoucan/glytoucan.github.io/issues/37
not structural data, so not in glytoucan scope (for now).

**Comment by aokinobu** [comment]
closing this for now, as external data partner should handle this.  this should be reopened if an API for taxonomy is necessary for partners.
