### ISSUE TITLE
新しいエントリーページの開発

### ISSUE THREAD

**Issue by shinmachi** [glytoucan/glytoucan.github.io#25]
ver2.0のエントリーページのデザイン
[スライド](https://docs.google.com/presentation/d/1XKVUXP9NAnoNpALcDc66LCQGWMkW3Wa0_NegOimevT4/edit?usp=sharing)

- データを取得するSPARQLが必要

**Comment by shinmachi** [comment]
スライドを元にエントリーページのレイアウトに沿ってサンプルが作られた。
開発途中のレイアウト画像
![new-glycanentry-capture_0414](https://cloud.githubusercontent.com/assets/4487545/14668482/7d344050-071f-11e6-9816-6ce61f88edf7.png)


表示には、togostanza-tsが使われている。

**Comment by shinmachi** [comment]
GlyTouCan Partner RDFについて

- [概要のスライド](https://docs.google.com/presentation/d/15bODD6gAhYA5bO4nVhGzPQ7OMLdp7CXyfVtxlbLOHoc/edit#slide=id.p)

- [Partner RDFについてのドキュメント](http://code.glytoucan.org/system/rdf/partnerRdf/)

- [Partner RDFをインサートするためのクエリ](http://code.glytoucan.org/system/sparql/partnerRdfInsertQuery/)
インサートクエリの数は、
BCSDB : 3
GlycomeDB : 2
GlycoEpitope : 3
GlycoNAVI : 1

- [GRAPH RDFについて](http://code.glytoucan.org/system/rdf/graphRdf/)
GRAPH RDFは、"From partner name"の部分の表示で使われる

NOTE：
Partner RDFとGRAPH RDFの両方のInsert queryを使う必要がある。


エントリーページに表示するためのSPARQLクエリをドキュメントに残した。
[sparql query for the glycan entry](http://code.glytoucan.org/system/glycanEntry/sparql/)

**Comment by shinmachi** [comment]
**新しいエントリーページの開発について**

簡単な説明のドキュメントを作成した。
- [ドキュメント](http://code.glytoucan.org/system/glycanEntry/)

**Comment by shinmachi** [comment]
Partner RDFを本番環境(ts.glytoucan.org)にロードした
`http://rdf.glytoucan.org/partner`　4 => partnerのmetadata graph
`http://rdf.glytoucan.org/partner/bcsdb`	71034
`http://rdf.glytoucan.org/partner/glycoepitope`	5611
`http://rdf.glytoucan.org/partner/glyconavi`	214549
`http://rdf.glytoucan.org/partner/glycome-db`	221171

**Comment by shinmachi** [comment]
[Specification of new entry contents](http://code.glytoucan.org/system/glycanEntry/)

新しいエントリーページで治したい箇所
１）コンテンツの一覧を表示する、entryNavの表示がずれいている
２）from [database name]のdatabase nameをクリックするとDBの説明とホームページのリンクを表示させる
- `http://rdf.glytoucan.org/partner`に、partner infoのデータがロードされている
- [Partner metadata doc](http://code.glytoucan.org/system/rdf/partnerMetadataRdf/)


３）External IDに、JCGGDB ID, PDB ID, を表示できるようにする
- JCGGDBは、GlycomeDBのリンクからのマッピングを利用できるが、そのマッピング


４）PubMed IDから文献のタイトルを取得する
-  REST APIを使えば取得できる
- しかし、このAPIを利用した仕組みをjs-stanzaでやるのか？
- それとも、rdf.glytoucan側でコントロールするのか？


５）Taxon IDを生物種名として表示できるようにする => 完了

**Comment by yamadaissaku** [comment]
考えたんだけど、GlyTouCanって国際糖鎖構造リポジトリだよね!　で、前はPDBjへのリンクがいいって言ってたけど、国際ってつくので、やっぱり三極のPDBへリンクしてユーザーに選んでもらうほうが良いように思えてきました。PDBjとは、今私がやってるentityへのリンクができそうなのでそれで差別化ができるので!　で、パートナーとしてのGlycoNAVIからRDFデータを取得できるようにしたいのです。

**Comment by shinmachi** [comment]
山田さん、コメントありがとうございます。
提案をまとめさせていただくと、

**External ID**

- PDB    
 - "PDB ID" + "PDB entry URL"   from  GlycomeDB

- PDBj   
 - "PDB ID" + "PDBj entry URL"  from  GlycoNAVI

以上のように、GlycomeDBでPDB情報、GlycoNAVIでPDBj情報をRDFで保持するという形になると考えています。

**Comment by yamadaissaku** [comment]
PDBの三極といったのは、wwwPDBのグループのPDBj, RCSB PDB, PDBeの３つです。それぞれが公開サイトを持っていて、データを共有しています。ユーザーは利用しやすいサイトを選んで利用していると思います。そのため、 PDBj, RCSB PDB, PDBeの３つのサイトへのリンクがあったほうがいいのでは？ということです。

**Comment by yamadaissaku** [comment]
また、PDBjについては、
"PDB ID"  "PDBj entry URL" from GlycoNAVI
"entity ID"  "PDBj entity entry URL" from GlycoNAVI
となる予定です。

**Comment by yamadaissaku** [comment]
あと、GlycoNAVIのエントリーへのリンクも可能にできますか？
"GlycoNAVI ID" "GlycoNAVI entry URL" from GlycoNAVI

**Comment by shinmachi** [comment]
ありがとうございます。
PDBeについては、今の所、ソースとなるパートナーがなかったため、省いております。また、GlycoNAVIのエントリーへのリンクも追加することもできます。追加方法としては、のぶさんが開発してる、APIを使った方法が予定されています。



更新

**External ID**

- Database name
- "Entry id" + "Entry URL"  from  "Partner name"

ex:

- PDB    
 - "PDB ID" + "PDB entry URL"   from  GlycomeDB

- PDBj   
 - "PDB ID" + "PDBj entry URL"  from  GlycoNAVI

- PDBj
 - "entity ID" +  "PDBj entity entry URL" from GlycoNAVI

- GlycoNAVI
 - "GlycoNAVI ID" + "GlycoNAVI entry URL" from GlycoNAVI

**Comment by yamadaissaku** [comment]
糖鎖の図(image)が２箇所で表示されているのですがこれは二箇所必要でしょうか？

**Comment by aokinobu** [comment]
http://beta.glytoucan.org/Structures/Entry/G24876BC
1. イメージは絶対パス使っています。相対パスにしてください。（/glycans/G24876BC/image?style=extended&format=png&notation=cfg）
2.データが存在しないフィールドを表示しないようにできますか？
Motif,Species,Literature,External ID

特に最初の３項目は現時点未定ですので、新しく登録された構造に関しては、表示できない確率はほとんどです。

**Comment by shinmachi** [comment]
確かに、糖鎖の図を二つ表示する意味が、これだと無いですね。一つだけでいいですね。

課題　　
- エントリーページでデータが無い項目は表示させない。

**Comment by shinmachi** [comment]
[Issues](https://docs.google.com/document/d/15Au6Mqt1dTilaJw7fa5BCeKmv45yZ1FWkpnSiFyEpH8/edit#heading=h.fpuxiuiiini7)
- summary label name
- contents

**Comment by aokinobu** [comment]
clicking on menu moves to place just below the title, can't see which section moved to. (low priority)

from GlycomeDB has no link or information about the partner.

**Comment by aokinobu** [comment]
TOCO released
