### ISSUE TITLE
new ts stanza repository

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#29]
[entry_htdocs.zip](https://github.com/glytoucan/glytoucan.github.io/files/254306/entry_htdocs.zip)
[entry_stanza_new.zip](https://github.com/glytoucan/glytoucan.github.io/files/254307/entry_stanza_new.zip)

・entry_stanza_new.zip
　build前のstanzaのソースです。
　dist以外の各ディレクトリがそれぞれの項目のstanzaになっています。
　ビルド(ts buildコマンドを実行)すると、distディレクトリ内にWeb components用のファイルが生成されます。
　（生成されたファイルはHTMLファイル内でimportして使います。）

・entry_htdocs.zip
　実際のHTMLページのデモです。

　※buildしたstanzaのファイルをindex.htmlからimportするため、必要なファイルをコピーしました。
　dist/stanza/(stanza名)/index.html　を　htdocs/stanza/(stanza名)/index.html　へコピーしてあります。
　dist/stanza/assets/components/以下のライブラリも、htdocs/assets/components/　へコピーしています。

　以下の3ファイルはstanzaと関係なく、ページのコンテンツを構成するためのファイルです。
　index.html
　htdocs/assets/css/entry.css
　htdocs/assets/js/entry.js　

　※index.html内の各コンポーネント呼び出し
（例：`<togostanza-structure acc="G00051MO" notation="cfg"></togostanza-structure>`）部分で、
　　stanzaへ渡す変数を直に書き込んでいますが、この部分はサーバ側で埋め込みをしてから出力していただければと思います。

**Comment by shinmachi** [comment]
GitHubにプッシュした
[glytoucan-js-stanza](https://github.com/glytoucan/glytoucan-js-stanza)

Docker化した
[docker-js-stanza](https://github.com/glytoucan/docker-js-stanza)

**Comment by shinmachi** [comment]
docker-compose-glytoucanに、js-stanzaのソースコードが含まれ、
js-stanzaは、docker-compose-glytoucanのサブモジュールとして利用している。
