### ISSUE TITLE
mass has_derivatization_type and how it is derived

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#30]
While in Sweden, there were questions as to how mass was calculated and after a closer look it needs to be clarified on whether this should be defined with the derivatization type predicate.

Mass is currently defined [here](http://code.glytoucan.org/rdf-ontology/rdf-doc.html#mass)

The default derivatization type is "none", what should this actually be?

Currently we are using WURCS framework calculation method.  What is the best way to describe how the mass is calculated?

**Comment by kiyoko** [comment]
I think "none" is correct. It's just the mass of the atoms.  For mass spectrometrists, they will want to know the mass after derivatization with various compounds, but this is currently outside the scope of GlyTouCan and should probably be a separate project.  Could also provide links to existing sites such as [http://web.expasy.org/glycomod/glycomod_masses.html](http://web.expasy.org/glycomod/glycomod_masses.html).

**Comment by aokinobu** [comment]
will stick with none
