### ISSUE TITLE
docker configurations need to be cleaned up

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#32]
a few issues:
1. new js stanza docker needs to be integrated
2. production environment needs to run on it's own images
3. production environment images should be versioned
4. docker file repositories are everywhere, copy into here and delete the repos.
5. setup a glycoinfo registry?  nice to have

**Comment by aokinobu** [comment]
@shinmachi please update here where the docker file for stanza is
please put into [this repository](https://github.com/glytoucan/docker-compose-glytoucan)

**Comment by shinmachi** [comment]
Update Dockerfile to "docker-compose-glytoucan" repository.

- js-stanza/Dockerfile

**Comment by aokinobu** [comment]
could there be a docker-compose.js-stanza.yml as well?  Please copy docker-compose.stanza.yml

**Comment by aokinobu** [comment]
docker-compose.yml fixed with different files for each subsystem, working on beta and prod now.  localization is still handled the same way, as automatically migrating language data is still a low priority now.

**Comment by aokinobu** [comment]
completed release of 1.2 with docker image method.  makefile created to push and jenkins executes the build.
