### ISSUE TITLE
Topology visualization

### ISSUE THREAD

**Issue by shinmachi** [glytoucan/glytoucan.github.io#42]
糖鎖構造間の関係性を可視化

![](http://code.glytoucan.org/images/system/subsumption_Glycosidic_topology.png)

**Comment by aokinobu** [comment]
batch process needed

**Comment by aokinobu** [comment]
[analysis document](http://code.glytoucan.org/system/rdf/subsumption_Glycosidic_topology/)

**Comment by aokinobu** [comment]
For the newly generated topology structures that are to be registered, the Contributor will be Administrator.

**Comment by aokinobu** [comment]
batch running on [kurobako](http://fly.glycoinfo.org:8891/sparql?default-graph-uri=&query=SELECT+%3Fg+%28COUNT%28%3Fg%29+as+%3Fcount%29+WHERE+%7B+GRAPH+%3Fg+%7B%3Fs+%3Fp+%3Fo%7D%7D+GROUP+BY+%3Fg&should-sponge=&format=text%2Fhtml&timeout=0&debug=on)
to point to this use ts change environment variable to:
SPRING_TRIPLESTORE_URL=jdbc:virtuoso://fly.glycoinfo.org:1112

**Comment by aokinobu** [comment]
[revised analysis document](https://docs.google.com/document/d/10JJNtu4Yw5LVapSB2x8XsR_aYXDRW4l1DFTU9KvfGk0/edit#)

**Comment by aokinobu** [comment]
http://fly.glycoinfo.org:90/
glytoucan on kuro

**Comment by aokinobu** [comment]
G00029MOがGlycosidic topologyを２つ持っている ->　完成
レベル2の認識によって自分自身をGlycosidic topologyとしてもっている糖鎖がある
Subsumptionのテストではこのレベル2が通っていてエラーが出ないが、現在localhost:8080の中には表示されていない
徳永さん：レベル判定が間違ったG番号の一覧を松原さんへ

リピート構造と環状構造は対象外にする

**Comment by aokinobu** [comment]
[ミーティングノート](https://docs.google.com/document/d/15Au6Mqt1dTilaJw7fa5BCeKmv45yZ1FWkpnSiFyEpH8/edit)

Validationの問題：現状のValidation方法では、new WurcsFactoryに任せているけど、Cyclicの場合、WurcsFactoryが違うWURCSを出力しているので、複数のTopologyを登録してしまっている。

更に、登録されたTopologyのTopologyを確認する時、違うWURCSを生成し、無限ループになってしまう現象が起きている？

他の構造が複数のTopologyを登録している、同じようなValidationの問題かどうかを確認中：
 PREFIX glytoucan:  <http://www.glytoucan.org/glyco/owl/glytoucan#>
Prefix rocs: <http://www.glycoinfo.org/glyco/owl/relation#>
SELECT ?out count(?s) WHERE {?s a rocs:Glycosidic_topology .
?out rocs:has_topology ?s .
 } group by ?out having count(?s) > 1 limit 100

**Comment by aokinobu** [comment]
問題なるWURCSをこのチェッカーで確認できます：http://wurcs-wg.org/tool/WURCSchecker.php

**Comment by aokinobu** [comment]
同じWURCSなのに、複数のAccessionNumberの現象も起きていた。確認中。

**Comment by aokinobu** [comment]
(上の問題はWURCSのCyclic問題ーCyclicを無視するようになっています)
released
