### ISSUE TITLE
supported sequence formats need to be displayed, replacing what is there now

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#44]
After biohackathon, it became clear what are the main formats that glytoucan should primarily support:
iupac, glycoct, wurcs
the main reasoning is for a historical perspective plus the need to relate back to the cheminfo world.

currently, the registration pages descriptions show other formats such as kcf and linearcode.  While these are supported, it should be explained that there are three main formats that have priority.  As the conversion work is still ongoing and constantly changing, it may be best to remove any specific formats on the initial registration page.  GlyTouCan is not a conversion engine, it should be clear what are the formats it should support for all users.  This responsibility should be passed on to the glyconvert project or rings for anyone interested in the conversion issues that exist.

Maybe just leaving very simplified sample formats to copy and paste.

**Comment by AokiCE** [comment]
Will work on this on Wednesday 9/21

**Comment by aokinobu** [comment]
released in 1.2.6-TOCO
