### ISSUE TITLE
filter glycan list by partner databases

### ISSUE THREAD

**Issue by kiyoko** [glytoucan/glytoucan.github.io#46]
Be able to select one or more partner databases to filter the glycan list to those entries that are found only in the selected database (or NOT by using logical functions)

**Comment by aokinobu** [comment]
@shinmachi how hard is this to implement?

**Comment by shinmachi** [comment]
I made sparql query for it filter, and send request for development to okuda-san and watanabe-san.

https://docs.google.com/document/d/1VQFnGLJ3KNcPUj8fqmnfe-161zh3pm73r3zsYPG4tco/edit?usp=sharing

**Comment by aokinobu** [comment]
released in 1.2.6-TOCO
