### ISSUE TITLE
Glycan list: default sorted order

### ISSUE THREAD

**Issue by kiyoko** [glytoucan/glytoucan.github.io#48]
Instead of showing glycan in increasing accession number, list glycans by decreasing date of registration, so that the newest registered glycans are shown on top.

**Comment by shinmachi** [comment]
modified glycan list file in rdf.glytoucan. I confirmed the newest registered glycans are shown on top in local env. So that it will be display on the beta.glytoucan.org soon.

**Comment by aokinobu** [comment]
confirmed on beta.  will be in next release (currently 1.2.3)

**Comment by aokinobu** [comment]
released
