### ISSUE TITLE
Text search needs more clear error messages

### ISSUE THREAD

**Issue by kiyoko** [glytoucan/glytoucan.github.io#59]
When I typed in the following IUPAC:　Man a1-6 (Man a1-3) Man a1-6 (Man a1-3) Man b1-4 GlcNAc b1-4 GlcpNAc
 (or any string for that matter) in the Text Search,  I get "Please input a sequence" error message.
It should provide a more appropriate error message, such as which format it expects.

![2016-07-14 09 16 06](https://cloud.githubusercontent.com/assets/993956/16824071/c1d3bd46-49a3-11e6-8c8c-2d0c6b98d158.png)

**Comment by aokinobu** [comment]
RES 1r:r1 REP REP1:8o(4+1)2d=-1--1 RES 2b:b-dgal-HEX-1:5 3s:n-acetyl 4b:b-dglc-HEX-1:5|6:a 5b:b-dgal-HEX-1:5 6s:n-acetyl 7b:a-dgal-HEX-1:5 8b:b-dglc-HEX-1:5 LIN 1:2d(2+1)3n 2:2o(3+1)4d 3:4o(4+1)5d 4:5d(2+1)6n 5:5o(4+1)7d 6:7o(3+1)8d

The demo glycoct works.  all conversion issues have it's own project in glyconvert.  Are you saying there is a problem with the error message?

**Comment by kiyoko** [comment]
Yes, there's a problem with the error message.

**Comment by aokinobu** [comment]
Currently in [beta](http://beta.glytoucan.org), ready for release.  In this case it cannot detect the format of the sequence so it returns CannotDetectFormat.

**Comment by aokinobu** [comment]
released in 1.2.7! properly detected an invalid glycoct in the heparin discussion.
