### ISSUE TITLE
expiring and archiving accession numbers

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#60]
As the conversion of glycoct to wurcs took place, some structures such as duplicates or erroneous  sequences were accepted and associated an id.  these need to be removed from core data.

need new functionality to:
1. remove the sequence and id from the core data and archive it
2. have an explanatory page describing what happened

in detail:
- specialized button on entry page for admin to expire the data
- archival of data web service:
  - move out of core data and put into new "archive" graph including all data associated with the Saccharide
    - sparql has "insert where using" functionality to gather all data and store into "archive"
    - "delete where" to remove
    - "select where" to confirm deleted.
- new page to list archived data, which could have a special entry page which just reads from archive
  - new page should also link to logs associated with the archived number

partner functionality will break, so admin should be responsible to communicate and explain the issue.  archived entry page will exist if a link is still necessary.

**Comment by kiyoko** [comment]
This should rarely need to be done (hopefully) so priority is low, except to just have the expired data available on a web page (for now) until you have time to work on this functionality.

**Comment by aokinobu** [comment]
@AokiCE could you please compare the accession numbers that have the same wurcs value and note if there is many differences between them?

**Comment by AokiCE** [comment]
details in #35

**Comment by AokiCE** [comment]
Finished comparing accession numbers with same wurcs value in spreadsheet from comment above in details.

**Comment by kiyoko** [comment]
@aokinobu this can be closed?
