### ISSUE TITLE
incorrect count of structures on top page

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#68]
top page is counting all sequence formats, not just wurcs.
sparql should be:

SELECT (COUNT(DISTINCT ?AccessionNumber) AS ?total)
      WHERE {
        ?glycan glytoucan:has_primary_id ?AccessionNumber .
       ?glycan glycan:has_glycosequence ?gseq .
       ?gseq glycan:has_sequence ?Seq .
       ?gseq glycan:in_carbohydrate_format glycan:carbohydrate_format_wurcs .
}

**Comment by shinmachi** [comment]
push the fixed sparql query in top_status_stanza
