### ISSUE TITLE
pubmed id registration

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#70]
register pubmed id with structure
add pubmed id to structure
edit pubmed id

**Comment by kiyoko** [comment]
also applying a single pubmed ID to several structures at once (in batch)

**Comment by aokinobu** [comment]
http://beta.glytoucan.org/Registries/supplement/G22768VO

**Comment by shinmachi** [comment]
developed LiteratureProcedure.class at gtc-liiterature
this class include methods such as add, delete and search.

**Comment by aokinobu** [comment]
registering now on beta, could use some design cleanup but this is ready for release.

This is going through the api interface, so if necessary, a batch can be created with the client.
I suggest creating a new issue once their is user demand for this to work with a CSV file, for instance.  This kind of functionality is already available via the CLI.

**Comment by aokinobu** [comment]
pages changed:
entry page:
http://beta.glytoucan.org/Structures/Glycans/G22768VO

new registration:
http://beta.glytoucan.org/Registries/supplement/G22768VO

new confirmation page
http://beta.glytoucan.org/Registries/supplement/G22768VO/confirmation

could use translation and design fixes

**Comment by AokiCE** [comment]
design fixed and added translation

**Comment by aokinobu** [comment]
1.2.7 released!  Registration only.  Editing and deleting will require more analysis.
However a last-minute update was added to register the contributor id with the publication id.
