### ISSUE TITLE
"From" field has no link to explanation of organization/database

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#72]
Should have description of who the organization is and links in order for users to decide if it is trustworthy information.

**Comment by shinmachi** [comment]
Add this partner explanation and can confirm http://beta.glytoucan.org/Structures/Glycans/G02657AK
 
![image](https://cloud.githubusercontent.com/assets/4487545/20621881/b1c59e24-b343-11e6-9364-1950d678a6d5.png)
