### ISSUE TITLE
no connection between database information in glycoRDF and partner graph name

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#74]
It is possible to create a method to "generate" the graph name from the current data, but it's best to store the name in a separate triple to make things clear.

Currently cannot insert into partner graphs even if user is member of the database.

**Comment by aokinobu** [comment]
Please update org.glycoinfo.rdf.glycan.DatabaseSelectSparql in [batch](http://github.com/glytoucan/batch) with the proper methods to select the data for a contributor.

Currently it does not have a test case, please create one if necessary.

**Comment by shinmachi** [comment]
There are **partner information RDF** and **partner member RDF** in Bitbucket repository
https://bitbucket.org/glytoucan/partner-info-rdf

This RDFs are to management RDF for partner.

**Comment by shinmachi** [comment]
graph name of the partner was generated from PartnerInfo.ttl
