### ISSUE TITLE
Translation: Partner Registration Request

### ISSUE THREAD

**Issue by shinmachi** [glytoucan/glytoucan.github.io#78]
It is necessary to translate partner registration request form for Japanese user.

http://code.glytoucan.org/partner/registration/

**Comment by AokiCE** [comment]
I will try to do this

**Comment by AokiCE** [comment]
Made copy of original in docs called "GlyTouCan Partner Form 日本語", will have to finish this on monday.

**Comment by AokiCE** [comment]
Finished translating to Japanese, please check grammar and vocabulary used, and edit if necessary. Thank you!

https://docs.google.com/forms/d/13zd1qwINy7c0zHeDa2BnE_JZr9Kemo0m4JkehkNAkZ8/edit

**Comment by shinmachi** [comment]
Thank you for your translation. I edited several description. 

https://docs.google.com/forms/d/13zd1qwINy7c0zHeDa2BnE_JZr9Kemo0m4JkehkNAkZ8/edit

**Comment by aokinobu** [comment]
please copy [registration page](https://github.com/glytoucan/glytoucan.github.io/blob/master/partner/registration.md) and make a registration_ja to embed for a japanese page.

**Comment by AokiCE** [comment]
will try to work on this on monday

**Comment by shinmachi** [comment]
I have written the doc for back up the Japanese.

https://docs.google.com/document/d/1ZkZj3wLLKP3sROTLGv9ANwVfEWLa2nTSQiYgZoGtf1s/edit?usp=sharing

**Comment by AokiCE** [comment]
Made [registration_ja.md](https://github.com/glytoucan/glytoucan.github.io/blob/master/partner/registration_ja.md) file. Form is embedded

**Comment by aokinobu** [comment]
[page](http://code.glytoucan.org/partner/registration_ja/)
