### ISSUE TITLE
grab graph not working on production with https

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#88]
Mixed Content: The page at 'https://glytoucan.org/GRAB_Graph/G00055MO' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-2.0.3.min.js'. This request has been blocked; the content must be served over HTTPS.
G00055MO:1 Mixed Content: The page at 'https://glytoucan.org/GRAB_Graph/G00055MO' was loaded over HTTPS, but requested an insecure script 'http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by aokinobu** [comment]
does this work?
https://raw.githubusercontent.com/cytoscape/cytoscape.js/master/dist/cytoscape.min.js

**Comment by Keiko-T** [comment]
I'm done.
Changed as follows for use with "https" and "http".
"//raw.githubusercontent.com/cytoscape/cytoscape.js/
master/dist/cytoscape.min.js
<https://raw.githubusercontent.com/cytoscape/cytoscape.js/master/dist/cytoscape.min.js>
"

2016-11-25 17:40 GMT+09:00 nobuyuki paul aoki <notifications@github.com>:

**Comment by aokinobu** [comment]
ok this is working on [test](https://test.glytoucan.org/GRAB_Graph/G00028MO).  Will be live in next release.

**Comment by aokinobu** [comment]
released in 1.2.7!
