### ISSUE TITLE
new Contact Us page

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#89]
keep email link but could also use:

https://gitter.im/glytoucan/comments

**Comment by aokinobu** [comment]
can create a page on glytoucan.github.io (code) to have a link for both on a new page.  Will link the main site to this one.

**Comment by AokiCE** [comment]
Okay, will make new page for both links when I come in on Monday!

**Comment by AokiCE** [comment]
http://code.glytoucan.org/contact/
Made the page, please add any needed changes in contact folder.

**Comment by aokinobu** [comment]
could it pop-out?  there is no way to back to glytoucan.org when you click on it.

**Comment by AokiCE** [comment]
Changed to a pop up window to the Contact Page. (pushed)
If you wanted a drop-up menu:
Trying to make a submenu in footer but text is different, not sure how to change.
Might need to add/change stuff to CSS? Am fiddling around with it now.

**Comment by AokiCE** [comment]
Was able to edit CSS for the Contact Us pop-up menu in footer. Branch is footermenu, not sure if you can see it? Will merge branch if needed.

**Comment by aokinobu** [comment]
released in 1.2.7!
