### ISSUE TITLE
rdf.glytoucan.orgをバラす

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#9]
どのクラスにバラすかはまだ設計中ですが、
glycan_motifとsaccharideを離すなどのSPARQLで（Construct？）移行必要があります。

この処理の設計をお願いします。

[ネーミング](http://code.glytoucan.org/system/name/)と[モチーフ](http://code.glytoucan.org/system/motif/)の設計に依存

**Comment by aokinobu** [comment]
[graph spreadsheet](https://docs.google.com/spreadsheets/d/1mZoOPL9OFlJkR6EXoRAQDaBM3Z-UdYmI3VfLGxLHnl8/edit#gid=0) と [document](https://docs.google.com/document/d/1MLwNt3OmPxqC2GciOtjZWkiE3eT7-phTl2bfW7ljzVo/edit) を一つにできませんか？

**Comment by shinmachi** [comment]
graph spreadsheetであるように、各GRAPHついての説明をmarkdownで先に作っておいて、
documentにあるように、<rdf.glytoucan.org>から各クラスをばらすためのSPARQLクエリを載せるやり方が思いつきますが、どうでしょうか？

**Comment by aokinobu** [comment]
よくみると、バラす作業では新しいGraphはない？そうであれば、これはそのままでいいと思います。
仕様的に決定している、各Graph（クラスはGlycoRDFの文ではない？）の説明文があれば助かりますが、今は優先ではない。

バージョン２のOntologyは影響するので今度の打ち合わせに使いましょう。
先日ポリシー的な話を[その資料](https://docs.google.com/document/d/1MLwNt3OmPxqC2GciOtjZWkiE3eT7-phTl2bfW7ljzVo/edit#heading=h.vdpsakn2ngko)にいれたほうがいいと思います。提案ですので、Wurcs側がオッケーであれば、決定になります。

**Comment by aokinobu** [comment]
やりましょうー。

- 資料の通り実行
- rdf.glytoucan.orgグラフをリネーム
- 動作確認

**Comment by shinmachi** [comment]
rdf.glytoucan.orgをテスト環境でばらしました
まずは、test GRAPHを作って、ばらす前とばらした後でトリプルの数に違いがないか調べました。
<http://rdf.glytoucan.org/core/test>
<http://rdf.glytoucan.org/sequence/glycoct/test>
<http://rdf.glytoucan.org/image/test>
<http://rdf.glytoucan.org/motif/test>

SPARQLで数を数えたところ、
どのGRAPHも、ばらす前とトリプル数が変化しませんでした。
[資料に残しました](https://docs.google.com/document/d/1MLwNt3OmPxqC2GciOtjZWkiE3eT7-phTl2bfW7ljzVo/edit#)

**Comment by aokinobu** [comment]
動作確認はベータ環境を確認すると同じです。rdf.glytoucan.orgをリネームして、消えていると同じようにして、ベータ環境は問題なく運用できますか？

全く同じ作業を本番環境に移します。問題なく運用は続くため、確認したほうがいいと思います。

ベータ環境ですので、データを移動したり、消したりしちゃっていいのです。

**Comment by aokinobu** [comment]
昨日お話したglycomedb のデータを整理する必要があります。
http://beta.glytoucan.org/Structures/Glycans/G00051MO
のGlycomeDBデータを見ると、例えばIdentiferとそのリンク先、どのようにRDF化する？

**Comment by yamadaissaku** [comment]
GlycomeDBでリンクしているリンクの意味は、それぞれのDBなどで異なりますので注意してくださいね。

**Comment by shinmachi** [comment]
gs2virをばらすためのInsert queryをcode.glytoucan.orgに記述しました。
[split graph](http://code.glytoucan.org/system/graph/splitGraph/l)

**Comment by shinmachi** [comment]
Insert queryの準備はできた
あとは本番環境で実行するだけ。

[Insert query](http://code.glytoucan.org/system/graph/splitGraph/)

実行するクエリは、
Saccharide
Resource entry
Glycosequence
Glycan motif
Component
の５つ

**Comment by aokinobu** [comment]
残りは、アプリ側、（Stanza,SparqlBean）rdf.glytoucan.orgのグラフを参照している部分をはずして、動作確認。

**Comment by aokinobu** [comment]
rdf.glytoucan.orgを使わないようにしましょう。Sparqlで見つかったら、外します。

**Comment by shinmachi** [comment]
本番環境のRDFデータセットを、コピーした環境（mac pro）を使って、[Insert sparql](http://code.glytoucan.org/system/graph/splitGraph/) を実行した。
結果、Glycan List, Motif List, entry pageが表示されたので、この環境では無事にインサートでした。

**Comment by shinmachi** [comment]
ローカル環境による動作確認　

環境
- ruby stanzaのsparql queryから `FROM <http://rdf.glytoucan.org>`　を削除している
- endpoint : http://test.ts.glytoucan.org/  
 - このテスト環境でもinsert sparqlを実行した。　


確認結果
- Glycan List  
 - motifs : ok
 - monosaccharides : ok
 - GlycoCT : ok
- Motif list : ok  
- Glycan entry  
 - GlycoCT : ok
 - motif : ok
 - monosaccharide composition : ok
 - visualization tool : ok
 - Linked DB (using accession number only) : ok

**Comment by shinmachi** [comment]
GRAPH をMoveする方法
例えば、

```
log_enable(2,1);
sparql 
move graph <http://rdf.glytoucan.org/core/test>
to graph <http://rdf.glytoucan.org/core/test/2>;

log_enable(2,1);
sparql 
move graph <http://rdf.glytoucan.org/core/test/2>
to graph <http://rdf.glytoucan.org/core/test>;
```

**Comment by shinmachi** [comment]
GRAPH をCopyする方法
例えば、<http://rdf.glytoucan.org/core/test>を　　
<http://rdf.glytoucan.org/core/test/2>にGRAPHをコピーする場合。　　
コピーするので、<http://rdf.glytoucan.org/core/test/2>にもともとあったトリプルは消去される。

```
log_enable(2,1);
sparql 
copy graph <http://rdf.glytoucan.org/core/test>
to graph <http://rdf.glytoucan.org/core/test/2>;
```

**Comment by aokinobu** [comment]
rdf.glytoucan.org graph is no longer used, core only.
