### ISSUE TITLE
"From Contributor" has a blank URL

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#92]
When you click on Contributor for registered users input data in literature, URL is blank.

This should link to a [document](http://code.glytoucan.org) explaining what Contributor is in more detail.

**Comment by shinmachi** [comment]
added the URL for the contributor. now it can confirm in the beta.glytoucan.org only.
http://beta.glytoucan.org/Structures/Glycans/G00055MO
