### ISSUE TITLE
Calendar panel for glytoucan schedule - new top page

### ISSUE THREAD

**Issue by shinmachi** [glytoucan/glytoucan.github.io#96]
The calendar panel is show glytoucan schedule.
- update
- power outage etc

**Comment by AokiCE** [comment]
I found that you can embed the google calendar and customize it too, but need to have the calendar set to public.
google calendar > select the small arrow on your name > select calendar settings > click on customize

**Comment by aokinobu** [comment]
google calendar embedded looks good.  Where to put it though?  Maybe placing it on the top page would be good?

**Comment by kiyoko** [comment]
Yeah, top page would be best

**Comment by AokiCE** [comment]
added the calendar to top page, showing agenda as default, users can choose to see month/week details. 
Calendar was also added to the footer as well, but put FAQ and User Guide into Menu pop-up to fit in footer.
also changed height on twitter to fit page, and moved the google search bar to the top. (pushed)

**Comment by aokinobu** [comment]
released in 1.2.7!
