### ISSUE TITLE
display a replacement error image when they cannot be generated

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#98]
## Need 

```gherkin
As a developer
I want to be able to display an image
So that users will be able to see something instead of a 0-byte broken image icon
```
## Deliverables

something like ![mascot](http://beta.glytoucan.org/img/logo_toucan.png) 

#### TODO
- default image file
- image file will be read whenever an exception occurs

#### Files
- Line 188 of GlycanQueryRest in client

**Comment by AokiCE** [comment]
Here is an image for replacing broken image icon:
![glytoucan_sad_icon](https://cloud.githubusercontent.com/assets/16686185/21877875/90b8f2c2-d8d1-11e6-921c-ce25bd7fbcf8.png)

**Comment by aokinobu** [comment]
![defaultimage](https://cloud.githubusercontent.com/assets/2884598/22097986/4ddca552-de67-11e6-9fa0-bb27752df315.png)

**Comment by aokinobu** [comment]
we should put a reason why this image is displayed in the faq?

**Comment by kiyoko** [comment]
yeah, maybe linked to this icon?

**Comment by AokiCE** [comment]
made a [FAQ](http://code.glytoucan.org/FAQ/no-image/) on the image for review.

**Comment by aokinobu** [comment]
completed in 1.2.9-TOCO
